on:
  workflow_call:
    inputs:
      node-version-file:
        description: "Path to the Node version file. Defaults to '.nvmrc'."
        default: .nvmrc
        type: string

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Install Browsers
        run: npx playwright install
      - name: Run Tests
        run: npm run test:ui
